version: '3'

services:
    express_starter:
        container_name: 'express_starter'
        build:
            context: .
            target: 'dev'
        volumes:
            - .:/app
        links:
            - express_starter_db
            - express_starter_test_db
        depends_on:
            - express_starter_db
            - express_starter_test_db
        ports:
            - 3000:3000
            - 9229:9229
        environment:
            DATABASE_URL: mysql://root:password@express_starter_test_db:3306/express_starter_test

    express_starter_db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: express_starter
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        volumes:
            - express_starter_db:/var/lib/mysql

    express_starter_test_db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - '3307:3306'
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: express_starter_test
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        volumes:
            - express_starter_test_db:/var/lib/mysql

volumes:
    express_starter_db:
        driver: local
    express_starter_test_db:
        driver: local
