-- AlterTable
ALTER TABLE `Post` ADD COLUMN `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    MODIFY `published` BOOLEAN NOT NULL DEFAULT false,
    MODIFY `content` VARCHAR(191) NULL;
